name: CD

on:
  push:
    branches: [ develop, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd-build:
    runs-on: ubuntu-latest
    name: Continuous deployment

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-node@v2.0.0

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Install prerequisites
      run: |
        pip install -r ./src/requirements.txt -r ./src/requirements-dev.txt
        npm install

    - name: Perform regression testing
      run: python -m pytest --rootdir=src || true

    - name: serverless create domain
      uses: jackdcasey/github-action@python3.8-nodejs13
      with:
        args: create_domain --stage ${{ steps.extract_branch.outputs.branch }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: serverless deploy
      uses: jackdcasey/github-action@python3.8-nodejs13
      with:
        args: deploy --stage ${{ steps.extract_branch.outputs.branch }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
