name: CD

on:
  push:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd-build:
    runs-on: ubuntu-latest
    name: Continuous deployment

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-node@v2.0.0

    - name: Install prerequisites
      run: pip install -r ./requirements.txt -r ./requirements-dev.txt

    - name: Perform regression testing
      run: python -m pytest
    
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage ${{ github.base_ref }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
