name: CD

on:
  pull_request:
    branches: [ master, develop ]
  # push:
  #   branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd-build:
    runs-on: ubuntu-latest
    name: Continuous deployment

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-node@v2

    - name: Install prerequisites
      run: |
        pip install -r ./requirements.txt -r ./requirements-dev.txt
        npm install --only=dev

    - name: Perform regression testing
      run: python -m pytest

    # - name: Configure AWS credentials from Test account
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1
    
    - name: Perform non-prod deployment
      run: echo 'TBD'
      if: ${{ github.base_ref == 'develop' }}
