name: CI

on:
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci-build:
    runs-on: ubuntu-latest
    name: Regression suite

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Run unit tests
      run: |
        pip install -r ./src/requirements.txt -r ./src/requirements-dev.txt 
        python -m pytest --rootdir=src || true